"""init migrate

Revision ID: cb67336e0037
Revises: 
Create Date: 2023-11-30 15:18:04.492113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb67336e0037'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_type', sa.String(), nullable=True),
    sa.Column('exercise', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gym locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('number_of_machines', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('membership_type', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_goal', sa.String(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_assignments_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assignments_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_name', sa.String(), nullable=True),
    sa.Column('gym_locations_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gym_locations_id'], ['gym locations.id'], name=op.f('fk_machines_gym_locations_id_gym locations')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('gym_location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gym_location_id'], ['gym locations.id'], name=op.f('fk_reviews_gym_location_id_gym locations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('gym_locations_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gym_locations_id'], ['gym locations.id'], name=op.f('fk_trainers_gym_locations_id_gym locations')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainers')
    op.drop_table('reviews')
    op.drop_table('machines')
    op.drop_table('assignments')
    op.drop_table('users')
    op.drop_table('gym locations')
    op.drop_table('exercises')
    # ### end Alembic commands ###
